name: arduino-build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd arduino
        ./scripts/pre-compile.sh
        ./scripts/compile.sh