name: Arduino CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd arduino
        ./scripts/pre-compile.sh
        ./scripts/compile.sh
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd arduino
        ./scripts/lint.sh